
services  :
  node-stripe-payment-microservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_stripe_payment_microservice
    ports:
      - "3300:3300"
    environment:
      - NODE_ENV=development
      - PORT=3300
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - CLIENT_URL=${CLIENT_URL:-http://localhost:8888}
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm run dev
    restart: unless-stopped